In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
online_retail = pd.read_excel(
    "https://raw.githubusercontent.com/Ivan-Curmi/FinalProject/main/Online%20Retail.xlsx",)

In [3]:
df= online_retail

In [4]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [5]:
df.shape

(541909, 8)

In [6]:
df.isna().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [7]:
df.nlargest(10,"Quantity")

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
540421,581483,23843,"PAPER CRAFT , LITTLE BIRDIE",80995,2011-12-09 09:15:00,2.08,16446.0,United Kingdom
61619,541431,23166,MEDIUM CERAMIC TOP STORAGE JAR,74215,2011-01-18 10:01:00,1.04,12346.0,United Kingdom
502122,578841,84826,ASSTD DESIGN 3D PAPER STICKERS,12540,2011-11-25 15:57:00,0.00,13256.0,United Kingdom
74614,542504,37413,NaN,5568,2011-01-28 12:03:00,0.00,NaN,United Kingdom
421632,573008,84077,WORLD WAR 2 GLIDERS ASSTD DESIGNS,4800,2011-10-27 12:26:00,0.21,12901.0,United Kingdom
206121,554868,22197,SMALL POPCORN HOLDER,4300,2011-05-27 10:52:00,0.72,13135.0,United Kingdom
220843,556231,85123A,?,4000,2011-06-09 15:04:00,0.00,NaN,United Kingdom
97432,544612,22053,EMPIRE DESIGN ROSETTE,3906,2011-02-22 10:43:00,0.82,18087.0,United Kingdom
270885,560599,18007,ESSENTIAL BALM 3.5g TIN IN ENVELOPE,3186,2011-07-19 17:04:00,0.06,14609.0,United Kingdom
52711,540815,21108,FAIRY CAKE FLANNEL ASSORTED COLOUR,3114,2011-01-11 12:55:00,2.10,15749.0,United Kingdom

In [8]:
df.nsmallest(10,"Quantity")

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
540422,C581484,23843,"PAPER CRAFT , LITTLE BIRDIE",-80995,2011-12-09 09:27:00,2.08,16446.0,United Kingdom
61624,C541433,23166,MEDIUM CERAMIC TOP STORAGE JAR,-74215,2011-01-18 10:17:00,1.04,12346.0,United Kingdom
225529,556690,23005,printing smudges/thrown away,-9600,2011-06-14 10:37:00,0.00,NaN,United Kingdom
225530,556691,23005,printing smudges/thrown away,-9600,2011-06-14 10:37:00,0.00,NaN,United Kingdom
4287,C536757,84347,ROTATING SILVER ANGELS T-LIGHT HLDR,-9360,2010-12-02 14:23:00,0.03,15838.0,United Kingdom
225528,556687,23003,Printing smudges/thrown away,-9058,2011-06-14 10:36:00,0.00,NaN,United Kingdom
115818,546152,72140F,throw away,-5368,2011-03-09 17:25:00,0.00,NaN,United Kingdom
431381,573596,79323W,"Unsaleable, destroyed.",-4830,2011-10-31 15:17:00,0.00,NaN,United Kingdom
341601,566768,16045,NaN,-3667,2011-09-14 17:53:00,0.00,NaN,United Kingdom
323458,565304,16259,NaN,-3167,2011-09-02 12:18:00,0.00,NaN,United Kingdom

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  datetime64[ns]
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 33.1+ MB

In [10]:
df = df.dropna()

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 406829 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    406829 non-null  object
 1   StockCode    406829 non-null  object
 2   Description  406829 non-null  object
 3   Quantity     406829 non-null  int64
 4   InvoiceDate  406829 non-null  datetime64[ns]
 5   UnitPrice    406829 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      406829 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 27.9+ MB

In [13]:
import pandas as pd
import nltk
nltk.download("stopwords")
nltk.download('punkt')
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from collections import Counter

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\ivanc\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\ivanc\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

In [14]:
# Preprocessing
stop_words = set(stopwords.words('english'))
stemmer = PorterStemmer()


def preprocess_text(text):
    words = nltk.word_tokenize(text.lower())
    words = [stemmer.stem(word)
             for word in words if word.isalpha() and word not in stop_words]
    return words

In [15]:
#2 nd trial

# Preprocessing
stop_words = set(stopwords.words('english'))
stemmer = PorterStemmer()


def preprocess_text(text):
    # Check if text is a string, and if not, return an empty list
    if not isinstance(text, str):
        return []

    words = nltk.word_tokenize(text.lower())
    words = [stemmer.stem(word)
             for word in words if word.isalpha() and word not in stop_words]
    return words


# Frequency Analysis
all_words = []
for desc in df['Description']:
    words = preprocess_text(desc)
    all_words.extend(words)

word_freq = Counter(all_words)

# Keyword Selection (top 5 keywords)
top_keywords = [word for word, freq in word_freq.most_common(15)]

print(top_keywords)

['set', 'bag', 'heart', 'red', 'retrospot', 'vintag', 'design', 'box', 'pink', 'christma', 'cake', 'white', 'metal', 'jumbo', 'lunch']

In [16]:
top_keywords

['set',
 'bag',
 'heart',
 'red',
 'retrospot',
 'vintag',
 'design',
 'box',
 'pink',
 'christma',
 'cake',
 'white',
 'metal',
 'jumbo',
 'lunch']

In [18]:
# Categorization (example mapping)
category_keywords = {
    'Decor': ['hang', 'holder', 'design', 'metal', 'ceramic', 'ornament', 'lantern', 'frame', 'knob', 'clock',  'LIGHT',  'HANGER', 'doiley',  'WALL DECOR',  'CANDLEHOLDER', 'CUSHION', 'VASE', 'quilt', 'ballons', 'doormat', 'CANDLE', 'CHRISTMAS', 'RACK', 'ALUMINIUM', 'STAR', 'KEY FOB', 'DRAWER', 'MAT', 'WICKER', 'SHELF', 'CABINET', 'STOOL', 'SPACE OWL', 'MIRROR', 'HOOK', 'INCENSE', 'DOORSTOP', 'EASTER', 'DECORATIONS', 'BABUSHKA', 'DOORSIGN', 'FLYING DUCKS', 'ART', 'PHOTO CUBE', 'SIGN'],
    'Stationery': ['paper', 'postage', 'pencil', 'Craft', 'pen', 'pencils', 'postage', 'blocks',  'paper', 'NOTEBOOK', 'PENS', 'erasers', 'STICKY NOTES', 'SCISSOR',  'MARKERS', 'FILE FOLDERS', 'BINDERS', 'STAMP SET', 'book', 'ribbon', 'LETTER ', 'STATIONERY', 'WRAP', 'CHALKBOARD', 'ruler', ' ORGANISER', 'WRITING'],
    'Kitchenware': ['cake', 'case', 'bottle', 'cutlery',   'mug', 'cake', 'cup', 'saucer', 'jug', 'beakers',  'bottle', 'plate', 'jar', 'KNIFE', 'CUTTING BOARD', 'diner', 'cookie', 'doilies', 'matches', 'bag', 'pannetone',  'apron',  'glass', 'POT',  'UTENSIL', 'COOKWARE SET',  'SPOON', 'BOWL',  'KITCHEN TOWEL',  'moulds',  'placemats',  'popcorn', 'HERB', 'CHOPPING BOARD', 'MOULD', 'TEA', 'SALT AND PEPPER', 'KITCHEN SCALES', 'SNACK', 'NAPKIN', 'EGG', ' FILLER PAD', 'WASHING', 'STRAWS', 'TISSUES', 'dish', 'WREATH', 'PARASOL', 'BUBBLES', 'BREAKFAST', 'JAM', 'FRYING PAN', 'KNICK KNACK', 'TRAY', 'TIN', 'BUNNIES'],
    'Toys and Games': ['game', 'lunch box', 'toys', 'puzzles', 'ACTION FIGURE', 'PLAYSET', 'LEGO SET', 'STUFFED ANIMAL', 'marbels', 'card', 'drawing', 'calculator', 'RC CAR', 'dominoes', 'party invites', 'tattoos', 'BIRTHDAY', 'HARMONICA', 'PARTY', 'BLOCK', ' PAINT', 'LUNCH BAG', 'PLAYHOUSE', 'CROQUET', 'BALLOON', 'SANDCASTLE', 'SNAKES & LADDERS', 'SKIPPING ROPE', 'STICKER', 'CHALK', 'SKITTLES', 'SPEAKER', 'BEAKER', 'BUBBLEGUM', 'TREASURE', 'SPACEBOY', 'INFLATABLE', 'CIRCUS', 'BICYCLE', 'SOFT TOY', 'BLACKBOARD', 'CIRCULAR', 'POLKADOT', 'BLACK BOARD', 'COLOURING', 'COASTER', 'BADGES'],
    'Clothing': ['T-SHIRT', 'DRESS', 'PANTS', 'JACKET', 'HAT', 'SCARF', 'SHOES', 'SOCKS'],
    'Beauty and Personal Care': ['SHAMPOO',  'LOTION', 'MAKEUP BRUSH', 'NAIL POLISH', 'TISSUE BOX', 'plaster', 'RAZOR',  'PERFUME', 'bath', 'HAIRDRYER', 'hand warmer', 'FACE MASK', 'gloss', 'JEWELLERY ', 'SEWING', 'HEART', 'FAN', 'PURSE', 'BRACELET', 'CREAM'],
    'Gardening': ['pitch', 'fork', 'GARDEN', 'PLANTER', 'WATERING ', 'GROW YOUR OWN FLOWERS'],
    'CARRIAGE': ['CARRIAGE'],
    'Others': ['SWAT', 'CAT FOOD', 'FLYTRAP', ' STORAGE', 'TRADITIONAL NAUGHTS & CROSSES', ' PAD', 'BICYCLE BELL', 'BUTTON', 'PEG', ' TAG', 'MAGNET', 'BACKPACK', 'PASSPORT COVER', 'TOOL SET', 'JUMBO SHOPPER', 'KNITTING', 'BELLS', 'PHOTO CLIP', 'TOAST ITS', 'KEEPSAKE', 'CROCHET', ' DISCO', 'CURTAIN', ''],
    'Discount': ['Discount'],
    'Manual': ['Manual'],
    'Bank Charges': ['Bank Charges'],

}

In [19]:
def classify_description(desc):
    if not isinstance(desc, str):
        return None  # or a default category if desired for non-string values

    keyword_matches = {category: sum(1 for keyword in keywords if keyword.upper() in desc)
                       for category, keywords in category_keywords.items()}
    if list(keyword_matches.values()) != [0,]*len(keyword_matches):
        return max(keyword_matches, key=keyword_matches.get)
    else:
        return None
    #return max(keyword_matches, key=keyword_matches.get)


df['Category'] = df['Description'].apply(classify_description)
print(df)

       InvoiceNo StockCode                          Description  Quantity  \
0         536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6
1         536365     71053                  WHITE METAL LANTERN         6
2         536365    84406B       CREAM CUPID HEARTS COAT HANGER         8
3         536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6
4         536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6
...          ...       ...                                  ...       ...
541904    581587     22613          PACK OF 20 SPACEBOY NAPKINS        12
541905    581587     22899         CHILDREN'S APRON DOLLY GIRL          6
541906    581587     23254        CHILDRENS CUTLERY DOLLY GIRL          4
541907    581587     23255      CHILDRENS CUTLERY CIRCUS PARADE         4
541908    581587     22138        BAKING SET 9 PIECE RETROSPOT          3

               InvoiceDate  UnitPrice  CustomerID         Country  \
0      2010-12-01 08:26:00       2.55     17850.0  United Kingdom
1      2010-12-01 08:26:00       3.39     17850.0  United Kingdom
2      2010-12-01 08:26:00       2.75     17850.0  United Kingdom
3      2010-12-01 08:26:00       3.39     17850.0  United Kingdom
4      2010-12-01 08:26:00       3.39     17850.0  United Kingdom
...                    ...        ...         ...             ...
541904 2011-12-09 12:50:00       0.85     12680.0          France
541905 2011-12-09 12:50:00       2.10     12680.0          France
541906 2011-12-09 12:50:00       4.15     12680.0          France
541907 2011-12-09 12:50:00       4.15     12680.0          France
541908 2011-12-09 12:50:00       4.95     12680.0          France

        total_revenue     Category
0               15.30        Decor
1               20.34        Decor
2               22.00        Decor
3               20.34  Kitchenware
4               20.34        Decor
...               ...          ...
541904          10.20  Kitchenware
541905          12.60  Kitchenware
541906          16.60  Kitchenware
541907          16.60  Kitchenware
541908          14.85  Kitchenware

[406829 rows x 10 columns]

C:\Users\ivanc\AppData\Local\Temp\ipykernel_12524\2368833152.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Category'] = df['Description'].apply(classify_description)

In [20]:
# Assuming you have a DataFrame 'df' with a 'Category' column

# Filter the DataFrame to get all items with 'None' category
uncategorized_items = df[df['Category'].isna() | (df['Category'] == 'None')]

# Print or use the 'uncategorized_items' DataFrame as needed
print(uncategorized_items)

Empty DataFrame
Columns: [InvoiceNo, StockCode, Description, Quantity, InvoiceDate, UnitPrice, CustomerID, Country, total_revenue, Category]
Index: []

In [21]:
df.sample(10)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,total_revenue,Category
81653,543170,22045,SPACEBOY GIFT WRAP,50,2011-02-04 09:03:00,0.42,17334.0,United Kingdom,21.00,Stationery
103825,545079,21826,EIGHT PIECE DINOSAUR SET,2,2011-02-28 10:30:00,1.25,18283.0,United Kingdom,2.50,Others
192306,553402,84692,BOX OF 24 COCKTAIL PARASOLS,1,2011-05-16 17:13:00,0.42,17898.0,United Kingdom,0.42,Kitchenware
416894,572563,23583,LUNCH BAG PAISLEY PARK,10,2011-10-25 09:31:00,1.65,12928.0,United Kingdom,16.50,Kitchenware
63374,541567,20724,RED RETROSPOT CHARLOTTE BAG,10,2011-01-19 11:51:00,0.85,12681.0,France,8.50,Kitchenware
460576,575919,22962,JAM JAR WITH PINK LID,48,2011-11-11 17:00:00,0.72,15311.0,United Kingdom,34.56,Kitchenware
180812,552358,22607,WOODEN ROUNDERS GARDEN SET,2,2011-05-09 12:20:00,9.95,15673.0,United Kingdom,19.90,Gardening
360818,568313,22594,CHRISTMAS GINGHAM TREE,12,2011-09-26 12:56:00,0.85,14908.0,United Kingdom,10.20,Decor
508607,579255,23313,VINTAGE CHRISTMAS BUNTING,2,2011-11-28 17:09:00,4.95,14901.0,United Kingdom,9.90,Decor
280555,561467,22384,LUNCH BAG PINK POLKADOT,20,2011-07-27 12:58:00,1.65,14040.0,United Kingdom,33.00,Toys and Games

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 406829 entries, 0 to 541908
Data columns (total 10 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   InvoiceNo      406829 non-null  object
 1   StockCode      406829 non-null  object
 2   Description    406829 non-null  object
 3   Quantity       406829 non-null  int64
 4   InvoiceDate    406829 non-null  datetime64[ns]
 5   UnitPrice      406829 non-null  float64
 6   CustomerID     406829 non-null  float64
 7   Country        406829 non-null  object
 8   total_revenue  406829 non-null  float64
 9   Category       406829 non-null  object
dtypes: datetime64[ns](1), float64(3), int64(1), object(5)
memory usage: 34.1+ MB

In [23]:
# Calculate total revenue and add it as a new column
df['total_revenue'] = df['Quantity'] * df['UnitPrice']

# Display the DataFrame with the new 'total_revenue' column
df.head()

C:\Users\ivanc\AppData\Local\Temp\ipykernel_12524\2311114690.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['total_revenue'] = df['Quantity'] * df['UnitPrice']

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,total_revenue,Category
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,15.30,Decor
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,Decor
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,22.00,Decor
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,Kitchenware
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,Decor

In [24]:
# Calculate total sales Revenue
total_sales = df['total_revenue'].sum()
print(f'Total Sales: {total_sales}')


# Calculate average daily sales Revenue
average_daily_sales = df['total_revenue'].mean()
print(f'Average Daily Sales: {average_daily_sales}')

Total Sales: 8300065.814000001
Average Daily Sales: 20.401853884555923

In [36]:
import pandas as pd


# Create two DataFrames for positive and negative quantities
df_positive_quantities = df.loc[df['Quantity'] > 0]
df_negative_quantities = df.loc[df['Quantity'] < 0]

# Display the resulting DataFrames
print("DataFrame with Positive Quantities:")
print(df_positive_quantities)

print("\nDataFrame with Negative Quantities:")
print(df_negative_quantities)

DataFrame with Positive Quantities:
       InvoiceNo StockCode                          Description  Quantity  \
0         536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6
1         536365     71053                  WHITE METAL LANTERN         6
2         536365    84406B       CREAM CUPID HEARTS COAT HANGER         8
3         536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6
4         536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6
...          ...       ...                                  ...       ...
541904    581587     22613          PACK OF 20 SPACEBOY NAPKINS        12
541905    581587     22899         CHILDREN'S APRON DOLLY GIRL          6
541906    581587     23254        CHILDRENS CUTLERY DOLLY GIRL          4
541907    581587     23255      CHILDRENS CUTLERY CIRCUS PARADE         4
541908    581587     22138        BAKING SET 9 PIECE RETROSPOT          3

               InvoiceDate  UnitPrice  CustomerID         Country  \
0      2010-12-01 08:26:00       2.55     17850.0  United Kingdom
1      2010-12-01 08:26:00       3.39     17850.0  United Kingdom
2      2010-12-01 08:26:00       2.75     17850.0  United Kingdom
3      2010-12-01 08:26:00       3.39     17850.0  United Kingdom
4      2010-12-01 08:26:00       3.39     17850.0  United Kingdom
...                    ...        ...         ...             ...
541904 2011-12-09 12:50:00       0.85     12680.0          France
541905 2011-12-09 12:50:00       2.10     12680.0          France
541906 2011-12-09 12:50:00       4.15     12680.0          France
541907 2011-12-09 12:50:00       4.15     12680.0          France
541908 2011-12-09 12:50:00       4.95     12680.0          France

        total_revenue     Category
0               15.30        Decor
1               20.34        Decor
2               22.00        Decor
3               20.34  Kitchenware
4               20.34        Decor
...               ...          ...
541904          10.20  Kitchenware
541905          12.60  Kitchenware
541906          16.60  Kitchenware
541907          16.60  Kitchenware
541908          14.85  Kitchenware

[397924 rows x 10 columns]

DataFrame with Negative Quantities:
       InvoiceNo StockCode                       Description  Quantity  \
141      C536379         D                          Discount        -1
154      C536383    35004C   SET OF 3 COLOURED  FLYING DUCKS        -1
235      C536391     22556    PLASTERS IN TIN CIRCUS PARADE        -12
236      C536391     21984  PACK OF 12 PINK PAISLEY TISSUES        -24
237      C536391     21983  PACK OF 12 BLUE PAISLEY TISSUES        -24
...          ...       ...                               ...       ...
540449   C581490     23144   ZINC T-LIGHT HOLDER STARS SMALL       -11
541541   C581499         M                            Manual        -1
541715   C581568     21258        VICTORIAN SEWING BOX LARGE        -5
541716   C581569     84978  HANGING HEART JAR T-LIGHT HOLDER        -1
541717   C581569     20979     36 PENCILS TUBE RED RETROSPOT        -5

               InvoiceDate  UnitPrice  CustomerID         Country  \
141    2010-12-01 09:41:00      27.50     14527.0  United Kingdom
154    2010-12-01 09:49:00       4.65     15311.0  United Kingdom
235    2010-12-01 10:24:00       1.65     17548.0  United Kingdom
236    2010-12-01 10:24:00       0.29     17548.0  United Kingdom
237    2010-12-01 10:24:00       0.29     17548.0  United Kingdom
...                    ...        ...         ...             ...
540449 2011-12-09 09:57:00       0.83     14397.0  United Kingdom
541541 2011-12-09 10:28:00     224.69     15498.0  United Kingdom
541715 2011-12-09 11:57:00      10.95     15311.0  United Kingdom
541716 2011-12-09 11:58:00       1.25     17315.0  United Kingdom
541717 2011-12-09 11:58:00       1.25     17315.0  United Kingdom

        total_revenue                  Category
141            -27.50                    Others
154             -4.65                     Decor
235            -19.80               Kitchenware
236             -6.96               Kitchenware
237             -6.96               Kitchenware
...               ...                       ...
540449          -9.13                     Decor
541541        -224.69                    Others
541715         -54.75  Beauty and Personal Care
541716          -1.25                     Decor
541717          -6.25                Stationery

[8905 rows x 10 columns]

In [37]:
# Sort the DataFrame by the maximum value in the 'Quantity' column
df_sorted1 = df_negative_quantities.sort_values(
    by='Quantity', key=lambda x: abs(x), ascending=False)

# Display the sorted DataFrame
print(df_sorted1)

       InvoiceNo StockCode                          Description  Quantity  \
540422   C581484     23843          PAPER CRAFT , LITTLE BIRDIE    -80995
61624    C541433     23166       MEDIUM CERAMIC TOP STORAGE JAR    -74215
4287     C536757     84347  ROTATING SILVER ANGELS T-LIGHT HLDR     -9360
160145   C550456     21108   FAIRY CAKE FLANNEL ASSORTED COLOUR     -3114
160144   C550456     21175          GIN + TONIC DIET METAL SIGN     -2000
...          ...       ...                                  ...       ...
177995   C552212     23126            FELTCRAFT GIRL AMELIE KIT        -1
349851   C567536     85048  15CM CHRISTMAS GLASS BALL 20 LIGHTS        -1
177220   C552047     22236       CAKE STAND 3 TIER MAGIC GARDEN        -1
349871   C567540     23173                REGENCY TEAPOT ROSES         -1
141      C536379         D                             Discount        -1

               InvoiceDate  UnitPrice  CustomerID         Country  \
540422 2011-12-09 09:27:00       2.08     16446.0  United Kingdom
61624  2011-01-18 10:17:00       1.04     12346.0  United Kingdom
4287   2010-12-02 14:23:00       0.03     15838.0  United Kingdom
160145 2011-04-18 13:08:00       2.10     15749.0  United Kingdom
160144 2011-04-18 13:08:00       1.85     15749.0  United Kingdom
...                    ...        ...         ...             ...
177995 2011-05-06 15:08:00       4.95     17422.0  United Kingdom
349851 2011-09-21 09:52:00       7.95     14284.0  United Kingdom
177220 2011-05-06 09:55:00      12.75     14796.0  United Kingdom
349871 2011-09-21 10:00:00       9.95     12384.0     Switzerland
141    2010-12-01 09:41:00      27.50     14527.0  United Kingdom

        total_revenue     Category
540422     -168469.60   Stationery
61624       -77183.60       Others
4287          -280.80        Decor
160145       -6539.40  Kitchenware
160144       -3700.00        Decor
...               ...          ...
177995          -4.95   Stationery
349851          -7.95        Decor
177220         -12.75  Kitchenware
349871          -9.95  Kitchenware
141            -27.50       Others

[8905 rows x 10 columns]

In [45]:

# Specify the index of the row you want to drop (e.g., index 2)
indices_to_drop = [540422, 61624]

# Use the drop method to remove the row by index
df_dropped = df_negative_quantities.drop(indices_to_drop)

# Display the DataFrame after dropping the row
print(df_dropped)
df_dropped.head()

       InvoiceNo StockCode                       Description  Quantity  \
141      C536379         D                          Discount        -1
154      C536383    35004C   SET OF 3 COLOURED  FLYING DUCKS        -1
235      C536391     22556    PLASTERS IN TIN CIRCUS PARADE        -12
236      C536391     21984  PACK OF 12 PINK PAISLEY TISSUES        -24
237      C536391     21983  PACK OF 12 BLUE PAISLEY TISSUES        -24
...          ...       ...                               ...       ...
540449   C581490     23144   ZINC T-LIGHT HOLDER STARS SMALL       -11
541541   C581499         M                            Manual        -1
541715   C581568     21258        VICTORIAN SEWING BOX LARGE        -5
541716   C581569     84978  HANGING HEART JAR T-LIGHT HOLDER        -1
541717   C581569     20979     36 PENCILS TUBE RED RETROSPOT        -5

               InvoiceDate  UnitPrice  CustomerID         Country  \
141    2010-12-01 09:41:00      27.50     14527.0  United Kingdom
154    2010-12-01 09:49:00       4.65     15311.0  United Kingdom
235    2010-12-01 10:24:00       1.65     17548.0  United Kingdom
236    2010-12-01 10:24:00       0.29     17548.0  United Kingdom
237    2010-12-01 10:24:00       0.29     17548.0  United Kingdom
...                    ...        ...         ...             ...
540449 2011-12-09 09:57:00       0.83     14397.0  United Kingdom
541541 2011-12-09 10:28:00     224.69     15498.0  United Kingdom
541715 2011-12-09 11:57:00      10.95     15311.0  United Kingdom
541716 2011-12-09 11:58:00       1.25     17315.0  United Kingdom
541717 2011-12-09 11:58:00       1.25     17315.0  United Kingdom

        total_revenue                  Category
141            -27.50                    Others
154             -4.65                     Decor
235            -19.80               Kitchenware
236             -6.96               Kitchenware
237             -6.96               Kitchenware
...               ...                       ...
540449          -9.13                     Decor
541541        -224.69                    Others
541715         -54.75  Beauty and Personal Care
541716          -1.25                     Decor
541717          -6.25                Stationery

[8903 rows x 10 columns]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,total_revenue,Category
141,C536379,D,Discount,-1,2010-12-01 09:41:00,27.50,14527.0,United Kingdom,-27.50,Others
154,C536383,35004C,SET OF 3 COLOURED FLYING DUCKS,-1,2010-12-01 09:49:00,4.65,15311.0,United Kingdom,-4.65,Decor
235,C536391,22556,PLASTERS IN TIN CIRCUS PARADE,-12,2010-12-01 10:24:00,1.65,17548.0,United Kingdom,-19.80,Kitchenware
236,C536391,21984,PACK OF 12 PINK PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom,-6.96,Kitchenware
237,C536391,21983,PACK OF 12 BLUE PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom,-6.96,Kitchenware

In [41]:
# Specify the index of the row you want to drop (e.g., index 2)
indices_to_drop = [540421, 61619]

# Use the drop method to remove the row by index
df_dropped1 = df_positive_quantities.drop(indices_to_drop)

# Display the DataFrame after dropping the row
print(df_dropped1)
df_dropped1.head()

       InvoiceNo StockCode                          Description  Quantity  \
0         536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6
1         536365     71053                  WHITE METAL LANTERN         6
2         536365    84406B       CREAM CUPID HEARTS COAT HANGER         8
3         536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6
4         536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6
...          ...       ...                                  ...       ...
541904    581587     22613          PACK OF 20 SPACEBOY NAPKINS        12
541905    581587     22899         CHILDREN'S APRON DOLLY GIRL          6
541906    581587     23254        CHILDRENS CUTLERY DOLLY GIRL          4
541907    581587     23255      CHILDRENS CUTLERY CIRCUS PARADE         4
541908    581587     22138        BAKING SET 9 PIECE RETROSPOT          3

               InvoiceDate  UnitPrice  CustomerID         Country  \
0      2010-12-01 08:26:00       2.55     17850.0  United Kingdom
1      2010-12-01 08:26:00       3.39     17850.0  United Kingdom
2      2010-12-01 08:26:00       2.75     17850.0  United Kingdom
3      2010-12-01 08:26:00       3.39     17850.0  United Kingdom
4      2010-12-01 08:26:00       3.39     17850.0  United Kingdom
...                    ...        ...         ...             ...
541904 2011-12-09 12:50:00       0.85     12680.0          France
541905 2011-12-09 12:50:00       2.10     12680.0          France
541906 2011-12-09 12:50:00       4.15     12680.0          France
541907 2011-12-09 12:50:00       4.15     12680.0          France
541908 2011-12-09 12:50:00       4.95     12680.0          France

        total_revenue     Category
0               15.30        Decor
1               20.34        Decor
2               22.00        Decor
3               20.34  Kitchenware
4               20.34        Decor
...               ...          ...
541904          10.20  Kitchenware
541905          12.60  Kitchenware
541906          16.60  Kitchenware
541907          16.60  Kitchenware
541908          14.85  Kitchenware

[397922 rows x 10 columns]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,total_revenue,Category
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,15.30,Decor
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,Decor
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,22.00,Decor
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,Kitchenware
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,Decor

In [42]:
# Sort by 'ColumnName' in ascending order
df = df.sort_values(by='Quantity')
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,total_revenue,Category
540422,C581484,23843,"PAPER CRAFT , LITTLE BIRDIE",-80995,2011-12-09 09:27:00,2.08,16446.0,United Kingdom,-168469.6,Stationery
61624,C541433,23166,MEDIUM CERAMIC TOP STORAGE JAR,-74215,2011-01-18 10:17:00,1.04,12346.0,United Kingdom,-77183.6,Others
4287,C536757,84347,ROTATING SILVER ANGELS T-LIGHT HLDR,-9360,2010-12-02 14:23:00,0.03,15838.0,United Kingdom,-280.8,Decor
160145,C550456,21108,FAIRY CAKE FLANNEL ASSORTED COLOUR,-3114,2011-04-18 13:08:00,2.10,15749.0,United Kingdom,-6539.4,Kitchenware
160144,C550456,21175,GIN + TONIC DIET METAL SIGN,-2000,2011-04-18 13:08:00,1.85,15749.0,United Kingdom,-3700.0,Decor

In [47]:
# Sort the DataFrame by the maximum value in the 'Quantity' column
df_sorted = df_positive_quantities.sort_values(
    by='Quantity', key=lambda x: abs(x), ascending=False)

# Display the sorted DataFrame
print(df_sorted)

       InvoiceNo StockCode                        Description  Quantity  \
540421    581483     23843        PAPER CRAFT , LITTLE BIRDIE     80995
61619     541431     23166     MEDIUM CERAMIC TOP STORAGE JAR     74215
502122    578841     84826     ASSTD DESIGN 3D PAPER STICKERS     12540
421632    573008     84077  WORLD WAR 2 GLIDERS ASSTD DESIGNS      4800
206121    554868     22197               SMALL POPCORN HOLDER      4300
...          ...       ...                                ...       ...
389620    570482     23380   PACK OF 12 VINTAGE DOILY TISSUES         1
132735    547689     21528     DAIRY MAID TRADITIONAL TEAPOT          1
389621    570482     22615  PACK OF 12 CIRCUS PARADE TISSUES          1
389622    570482     23377      PACK OF 12 DOLLY GIRL TISSUES         1
109150    545587     21870   I CAN ONLY PLEASE ONE PERSON MUG         1

               InvoiceDate  UnitPrice  CustomerID         Country  \
540421 2011-12-09 09:15:00       2.08     16446.0  United Kingdom
61619  2011-01-18 10:01:00       1.04     12346.0  United Kingdom
502122 2011-11-25 15:57:00       0.00     13256.0  United Kingdom
421632 2011-10-27 12:26:00       0.21     12901.0  United Kingdom
206121 2011-05-27 10:52:00       0.72     13135.0  United Kingdom
...                    ...        ...         ...             ...
389620 2011-10-10 17:00:00       0.39     17459.0  United Kingdom
132735 2011-03-24 14:55:00       6.95     17757.0  United Kingdom
389621 2011-10-10 17:00:00       0.39     17459.0  United Kingdom
389622 2011-10-10 17:00:00       0.39     17459.0  United Kingdom
109150 2011-03-04 09:46:00       1.25     14796.0  United Kingdom

        total_revenue     Category
540421      168469.60   Stationery
61619        77183.60       Others
502122           0.00        Decor
421632        1008.00        Decor
206121        3096.00        Decor
...               ...          ...
389620           0.39  Kitchenware
132735           6.95  Kitchenware
389621           0.39  Kitchenware
389622           0.39  Kitchenware
109150           1.25  Kitchenware

[397924 rows x 10 columns]

In [39]:
df_sorted1.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,total_revenue,Category
540422,C581484,23843,"PAPER CRAFT , LITTLE BIRDIE",-80995,2011-12-09 09:27:00,2.08,16446.0,United Kingdom,-168469.6,Stationery
61624,C541433,23166,MEDIUM CERAMIC TOP STORAGE JAR,-74215,2011-01-18 10:17:00,1.04,12346.0,United Kingdom,-77183.6,Others
4287,C536757,84347,ROTATING SILVER ANGELS T-LIGHT HLDR,-9360,2010-12-02 14:23:00,0.03,15838.0,United Kingdom,-280.8,Decor
160145,C550456,21108,FAIRY CAKE FLANNEL ASSORTED COLOUR,-3114,2011-04-18 13:08:00,2.10,15749.0,United Kingdom,-6539.4,Kitchenware
160144,C550456,21175,GIN + TONIC DIET METAL SIGN,-2000,2011-04-18 13:08:00,1.85,15749.0,United Kingdom,-3700.0,Decor

In [48]:
df_sorted.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,total_revenue,Category
540421,581483,23843,"PAPER CRAFT , LITTLE BIRDIE",80995,2011-12-09 09:15:00,2.08,16446.0,United Kingdom,168469.6,Stationery
61619,541431,23166,MEDIUM CERAMIC TOP STORAGE JAR,74215,2011-01-18 10:01:00,1.04,12346.0,United Kingdom,77183.6,Others
502122,578841,84826,ASSTD DESIGN 3D PAPER STICKERS,12540,2011-11-25 15:57:00,0.00,13256.0,United Kingdom,0.0,Decor
421632,573008,84077,WORLD WAR 2 GLIDERS ASSTD DESIGNS,4800,2011-10-27 12:26:00,0.21,12901.0,United Kingdom,1008.0,Decor
206121,554868,22197,SMALL POPCORN HOLDER,4300,2011-05-27 10:52:00,0.72,13135.0,United Kingdom,3096.0,Decor

In [25]:
# Group by 'Country' and calculate total sales
total_sales_per_country = df.groupby(
    'Country')['total_revenue'].sum().reset_index()

# Sort the DataFrame by 'total_revenue' in descending order
total_sales_per_country = total_sales_per_country.sort_values(
    by='total_revenue', ascending=False)

# Display the total sales per country
print(total_sales_per_country)

                 Country  total_revenue
35        United Kingdom    6767873.394
23           Netherlands     284661.540
10                  EIRE     250285.220
14               Germany     221698.210
13                France     196712.840
0              Australia     137077.270
32           Switzerland      55739.400
30                 Spain      54774.580
3                Belgium      40910.960
31                Sweden      36595.910
19                 Japan      35340.620
24                Norway      35163.460
26              Portugal      29059.810
12               Finland      22326.740
6        Channel Islands      20086.290
9                Denmark      18768.140
18                 Italy      16890.510
7                 Cyprus      12946.290
1                Austria      10154.320
29             Singapore       9120.390
25                Poland       7213.140
17                Israel       6994.250
15                Greece       4710.520
16               Iceland       4310.000
5                 Canada       3666.380
36           Unspecified       2667.070
22                 Malta       2505.470
34  United Arab Emirates       1902.280
33                   USA       1730.920
20               Lebanon       1693.880
21             Lithuania       1661.060
11    European Community       1291.750
4                 Brazil       1143.600
27                   RSA       1002.310
8         Czech Republic        707.720
2                Bahrain        548.400
28          Saudi Arabia        131.170

In [26]:
# Group by 'Customer' and calculate total sales revenue per Customer
total_sales_per_customer = df.groupby(
    'CustomerID')['total_revenue'].sum().reset_index()

# Display the total sales revenue per customer
print(total_sales_per_customer)

      CustomerID  total_revenue
0        12346.0           0.00
1        12347.0        4310.00
2        12348.0        1797.24
3        12349.0        1757.55
4        12350.0         334.40
...          ...            ...
4367     18280.0         180.60
4368     18281.0          80.82
4369     18282.0         176.60
4370     18283.0        2094.88
4371     18287.0        1837.28

[4372 rows x 2 columns]

In [27]:
# Group by 'Country' and 'Customer' and calculate total sales revenue
total_sales_per_customer = df.groupby(['Country', 'CustomerID'])[
    'total_revenue'].sum().sort_values(ascending=False).reset_index()

# Display the total sales revenuew per customer with country
print(total_sales_per_customer)

             Country  CustomerID  total_revenue
0        Netherlands     14646.0      279489.02
1     United Kingdom     18102.0      256438.49
2     United Kingdom     17450.0      187482.17
3               EIRE     14911.0      132572.62
4          Australia     12415.0      123725.45
...              ...         ...            ...
4375           Spain     12503.0       -1126.00
4376  United Kingdom     17603.0       -1165.30
4377  United Kingdom     14213.0       -1192.20
4378  United Kingdom     15369.0       -1592.49
4379  United Kingdom     17448.0       -4287.63

[4380 rows x 3 columns]

In [28]:
# Calculate total sales Volume
total_sales = df['Quantity'].sum()
print(f'Total Sales: {total_sales}')


# Calculate average daily sales
average_daily_sales = df['Quantity'].mean()
print(f'Average Daily Sales: {average_daily_sales}')

Total Sales: 4906888
Average Daily Sales: 12.06130339774205

In [29]:
# Group by 'Country' and calculate total sales volume
total_sales_per_country = df.groupby(
    'Country')['Quantity'].sum().sort_values(ascending=False).reset_index()

# Display the total sales volume per country
print(total_sales_per_country)

                 Country  Quantity
0         United Kingdom   4008533
1            Netherlands    200128
2                   EIRE    136329
3                Germany    117448
4                 France    109848
5              Australia     83653
6                 Sweden     35637
7            Switzerland     29778
8                  Spain     26824
9                  Japan     25218
10               Belgium     23152
11                Norway     19247
12              Portugal     16044
13               Finland     10666
14       Channel Islands      9479
15               Denmark      8188
16                 Italy      7999
17                Cyprus      6317
18             Singapore      5234
19               Austria      4827
20                Israel      3990
21                Poland      3653
22                Canada      2763
23               Iceland      2458
24           Unspecified      1789
25                Greece      1556
26                   USA      1034
27  United Arab Emirates       982
28                 Malta       944
29             Lithuania       652
30        Czech Republic       592
31    European Community       497
32               Lebanon       386
33                Brazil       356
34                   RSA       352
35               Bahrain       260
36          Saudi Arabia        75

In [30]:
# Group by 'Customer' and calculate total sales volume per Customer
total_sales_per_customer = df.groupby(
    'CustomerID')['Quantity'].sum().sort_values(ascending=False).reset_index()

# Display the total sales volume per customer
print(total_sales_per_customer)

      CustomerID  Quantity
0        14646.0    196719
1        12415.0     77242
2        14911.0     77180
3        17450.0     69029
4        18102.0     64122
...          ...       ...
4367     16252.0      -158
4368     16742.0      -189
4369     14213.0      -244
4370     15823.0      -283
4371     16546.0      -303

[4372 rows x 2 columns]

In [31]:
# Group by 'Customer' and calculate total sales volume per Customer
total_sales_per_customer = df.groupby(
    'CustomerID')['Quantity'].count().sort_values(ascending=False).reset_index()

# Display the total sales volume per customer
print(total_sales_per_customer)

      CustomerID  Quantity
0        17841.0      7983
1        14911.0      5903
2        14096.0      5128
3        12748.0      4642
4        14606.0      2782
...          ...       ...
4367     14119.0         1
4368     13747.0         1
4369     15590.0         1
4370     15562.0         1
4371     17925.0         1

[4372 rows x 2 columns]

In [32]:
# Group by 'Country' and 'Customer' and calculate total sales Volume
total_sales_per_customer = df.groupby(['Country', 'CustomerID'])[
    'Quantity'].sum().sort_values(ascending=False).reset_index()

# Display the total sales Volume per customer with country
print(total_sales_per_customer)

             Country  CustomerID  Quantity
0        Netherlands     14646.0    196719
1          Australia     12415.0     77242
2               EIRE     14911.0     77180
3     United Kingdom     17450.0     69029
4     United Kingdom     18102.0     64122
...              ...         ...       ...
4375  United Kingdom     16252.0      -158
4376  United Kingdom     16742.0      -189
4377  United Kingdom     14213.0      -244
4378  United Kingdom     15823.0      -283
4379  United Kingdom     16546.0      -303

[4380 rows x 3 columns]

In [33]:
# Group by 'Category and calculate total sales Volume
total_sales_per_category = df.groupby(['Category'])[
    'Quantity'].sum().sort_values(ascending=False).reset_index()

# Display the total sales Volume per customer with country
print(total_sales_per_category)

                   Category  Quantity
0                     Decor   1906031
1               Kitchenware   1468566
2                Stationery    573536
3            Toys and Games    460066
4                    Others    344189
5  Beauty and Personal Care    126879
6                 Gardening     26300
7                  Clothing      1188
8                  CARRIAGE       133

In [49]:
df_negative_quantities.describe()

,Quantity,InvoiceDate,UnitPrice,CustomerID,total_revenue
count,8905.000000,8905,8905.000000,8905.000000,8905.000000
mean,-30.859966,2011-06-27 06:17:46.598540032,18.845519,14991.667266,-68.651554
min,-80995.000000,2010-12-01 09:41:00,0.010000,12346.000000,-168469.600000
25%,-6.000000,2011-03-22 16:07:00,1.450000,13510.000000,-17.000000
50%,-2.000000,2011-07-11 13:51:00,2.950000,14895.000000,-8.500000
75%,-1.000000,2011-10-06 20:36:00,4.950000,16393.000000,-3.300000
max,-1.000000,2011-12-09 11:58:00,38970.000000,18282.000000,-0.120000
std,1170.154939,NaN,444.366043,1706.772357,2019.177682

In [50]:
# Group by 'Category and calculate total sales Volume
returns = df_negative_quantities.groupby(['Category'])[
    'Quantity'].sum().sort_values(ascending=True).reset_index()

# Display the total sales Volume per customer with country
print(returns)

                   Category  Quantity
0                Stationery    -95123
1                    Others    -85941
2                     Decor    -50116
3               Kitchenware    -37190
4            Toys and Games     -4180
5  Beauty and Personal Care     -2013
6                 Gardening      -231
7                  Clothing       -13
8                  CARRIAGE        -1

In [51]:
# Group by 'Category and calculate total sales revenue
returns = df_negative_quantities.groupby(['Category'])[
    'total_revenue'].sum().sort_values(ascending=True).reset_index()

# Display the total sales Volume per customer with country
print(returns)

                   Category  total_revenue
0                    Others     -216937.42
1                Stationery     -199153.67
2                     Decor      -92806.07
3               Kitchenware      -91539.09
4            Toys and Games       -5068.36
5  Beauty and Personal Care       -4951.57
6                 Gardening        -813.16
7                  CARRIAGE         -50.00
8                  Clothing         -22.75

In [52]:
# Sort the DataFrame by the maximum value in the 'Quantity' column
df_sorted = df_positive_quantities.sort_values(
    by='Quantity', key=lambda x: abs(x), ascending=False)

# Display the sorted DataFrame
print(df_sorted)

       InvoiceNo StockCode                        Description  Quantity  \
540421    581483     23843        PAPER CRAFT , LITTLE BIRDIE     80995
61619     541431     23166     MEDIUM CERAMIC TOP STORAGE JAR     74215
502122    578841     84826     ASSTD DESIGN 3D PAPER STICKERS     12540
421632    573008     84077  WORLD WAR 2 GLIDERS ASSTD DESIGNS      4800
206121    554868     22197               SMALL POPCORN HOLDER      4300
...          ...       ...                                ...       ...
389620    570482     23380   PACK OF 12 VINTAGE DOILY TISSUES         1
132735    547689     21528     DAIRY MAID TRADITIONAL TEAPOT          1
389621    570482     22615  PACK OF 12 CIRCUS PARADE TISSUES          1
389622    570482     23377      PACK OF 12 DOLLY GIRL TISSUES         1
109150    545587     21870   I CAN ONLY PLEASE ONE PERSON MUG         1

               InvoiceDate  UnitPrice  CustomerID         Country  \
540421 2011-12-09 09:15:00       2.08     16446.0  United Kingdom
61619  2011-01-18 10:01:00       1.04     12346.0  United Kingdom
502122 2011-11-25 15:57:00       0.00     13256.0  United Kingdom
421632 2011-10-27 12:26:00       0.21     12901.0  United Kingdom
206121 2011-05-27 10:52:00       0.72     13135.0  United Kingdom
...                    ...        ...         ...             ...
389620 2011-10-10 17:00:00       0.39     17459.0  United Kingdom
132735 2011-03-24 14:55:00       6.95     17757.0  United Kingdom
389621 2011-10-10 17:00:00       0.39     17459.0  United Kingdom
389622 2011-10-10 17:00:00       0.39     17459.0  United Kingdom
109150 2011-03-04 09:46:00       1.25     14796.0  United Kingdom

        total_revenue     Category
540421      168469.60   Stationery
61619        77183.60       Others
502122           0.00        Decor
421632        1008.00        Decor
206121        3096.00        Decor
...               ...          ...
389620           0.39  Kitchenware
132735           6.95  Kitchenware
389621           0.39  Kitchenware
389622           0.39  Kitchenware
109150           1.25  Kitchenware

[397924 rows x 10 columns]

In [53]:
# Sort the DataFrame by the maximum value in the 'Quantity' column
df_sorted1 = df_negative_quantities.sort_values(
    by='Quantity', key=lambda x: abs(x), ascending=False)

# Display the sorted DataFrame
print(df_sorted1)

       InvoiceNo StockCode                          Description  Quantity  \
540422   C581484     23843          PAPER CRAFT , LITTLE BIRDIE    -80995
61624    C541433     23166       MEDIUM CERAMIC TOP STORAGE JAR    -74215
4287     C536757     84347  ROTATING SILVER ANGELS T-LIGHT HLDR     -9360
160145   C550456     21108   FAIRY CAKE FLANNEL ASSORTED COLOUR     -3114
160144   C550456     21175          GIN + TONIC DIET METAL SIGN     -2000
...          ...       ...                                  ...       ...
177995   C552212     23126            FELTCRAFT GIRL AMELIE KIT        -1
349851   C567536     85048  15CM CHRISTMAS GLASS BALL 20 LIGHTS        -1
177220   C552047     22236       CAKE STAND 3 TIER MAGIC GARDEN        -1
349871   C567540     23173                REGENCY TEAPOT ROSES         -1
141      C536379         D                             Discount        -1

               InvoiceDate  UnitPrice  CustomerID         Country  \
540422 2011-12-09 09:27:00       2.08     16446.0  United Kingdom
61624  2011-01-18 10:17:00       1.04     12346.0  United Kingdom
4287   2010-12-02 14:23:00       0.03     15838.0  United Kingdom
160145 2011-04-18 13:08:00       2.10     15749.0  United Kingdom
160144 2011-04-18 13:08:00       1.85     15749.0  United Kingdom
...                    ...        ...         ...             ...
177995 2011-05-06 15:08:00       4.95     17422.0  United Kingdom
349851 2011-09-21 09:52:00       7.95     14284.0  United Kingdom
177220 2011-05-06 09:55:00      12.75     14796.0  United Kingdom
349871 2011-09-21 10:00:00       9.95     12384.0     Switzerland
141    2010-12-01 09:41:00      27.50     14527.0  United Kingdom

        total_revenue     Category
540422     -168469.60   Stationery
61624       -77183.60       Others
4287          -280.80        Decor
160145       -6539.40  Kitchenware
160144       -3700.00        Decor
...               ...          ...
177995          -4.95   Stationery
349851          -7.95        Decor
177220         -12.75  Kitchenware
349871          -9.95  Kitchenware
141            -27.50       Others

[8905 rows x 10 columns]

In [54]:

# Sort the DataFrame by 'Sales' column in descending order
sorted_df = df_positive_quantities.sort_values(by='Quantity', ascending=False)

# Select the top 10 products
top_10_products = sorted_df.head(10)

# Display the top 10 products
print(top_10_products)

       InvoiceNo StockCode                          Description  Quantity  \
540421    581483     23843          PAPER CRAFT , LITTLE BIRDIE     80995
61619     541431     23166       MEDIUM CERAMIC TOP STORAGE JAR     74215
502122    578841     84826       ASSTD DESIGN 3D PAPER STICKERS     12540
421632    573008     84077    WORLD WAR 2 GLIDERS ASSTD DESIGNS      4800
206121    554868     22197                 SMALL POPCORN HOLDER      4300
97432     544612     22053                EMPIRE DESIGN ROSETTE      3906
270885    560599     18007  ESSENTIAL BALM 3.5g TIN IN ENVELOPE      3186
52711     540815     21108   FAIRY CAKE FLANNEL ASSORTED COLOUR      3114
160546    550461     21108   FAIRY CAKE FLANNEL ASSORTED COLOUR      3114
433788    573995     16014          SMALL CHINESE STYLE SCISSOR      3000

               InvoiceDate  UnitPrice  CustomerID         Country  \
540421 2011-12-09 09:15:00       2.08     16446.0  United Kingdom
61619  2011-01-18 10:01:00       1.04     12346.0  United Kingdom
502122 2011-11-25 15:57:00       0.00     13256.0  United Kingdom
421632 2011-10-27 12:26:00       0.21     12901.0  United Kingdom
206121 2011-05-27 10:52:00       0.72     13135.0  United Kingdom
97432  2011-02-22 10:43:00       0.82     18087.0  United Kingdom
270885 2011-07-19 17:04:00       0.06     14609.0  United Kingdom
52711  2011-01-11 12:55:00       2.10     15749.0  United Kingdom
160546 2011-04-18 13:20:00       2.10     15749.0  United Kingdom
433788 2011-11-02 11:24:00       0.32     16308.0  United Kingdom

        total_revenue     Category
540421      168469.60   Stationery
61619        77183.60       Others
502122           0.00        Decor
421632        1008.00        Decor
206121        3096.00        Decor
97432         3202.92        Decor
270885         191.16  Kitchenware
52711         6539.40  Kitchenware
160546        6539.40  Kitchenware
433788         960.00   Stationery

In [68]:

# Sort the DataFrame by 'Sales' column in descending order
sorted_df = df_positive_quantities.sort_values(by='Quantity', ascending=True)

# Select the top 10 products
less_10_products = sorted_df.head(10)

# Display the top 10 products
print(less_10_products)

       InvoiceNo StockCode                         Description  Quantity  \
213209    555524     23173               REGENCY TEAPOT ROSES          1
171892    551471    85199S   SMALL HANGING IVORY/RED WOOD BIRD         1
171894    551471     22083           PAPER CHAIN KIT RETROSPOT         1
93808     544312    47566B              TEA TIME PARTY BUNTING         1
171895    551471     22558     CLOTHES PEGS RETROSPOT PACK 24          1
171896    551471     21447    12 IVORY ROSE PEG PLACE SETTINGS         1
171897    551471     22522            CHILDS GARDEN FORK BLUE          1
171898    551471     22520          CHILDS GARDEN TROWEL BLUE          1
426934    573369     23328  SET 6 SCHOOL MILK BOTTLES IN CRATE         1
93802     544311     22978                  PANTRY ROLLING PIN         1

               InvoiceDate  UnitPrice  CustomerID         Country  \
213209 2011-06-05 11:37:00       9.95     16923.0  United Kingdom
171892 2011-04-28 16:40:00       0.42     16370.0  United Kingdom
171894 2011-04-28 16:40:00       2.95     16370.0  United Kingdom
93808  2011-02-17 14:26:00       4.95     17841.0  United Kingdom
171895 2011-04-28 16:40:00       1.65     16370.0  United Kingdom
171896 2011-04-28 16:40:00       1.25     16370.0  United Kingdom
171897 2011-04-28 16:40:00       0.85     16370.0  United Kingdom
171898 2011-04-28 16:40:00       0.85     16370.0  United Kingdom
426934 2011-10-30 13:19:00       3.75     16049.0  United Kingdom
93802  2011-02-17 14:19:00       3.75     17841.0  United Kingdom

        total_revenue     Category
213209           9.95  Kitchenware
171892           0.42        Decor
171894           2.95   Stationery
93808            4.95  Kitchenware
171895           1.65       Others
171896           1.25       Others
171897           0.85    Gardening
171898           0.85    Gardening
426934           3.75  Kitchenware
93802            3.75       Others

In [56]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OrdinalEncoder, StandardScaler
from sklearn.pipeline import make_pipeline
from sklearn.tree import DecisionTreeRegressor
from sklearn.linear_model import LinearRegression, SGDRegressor
from sklearn.metrics import mean_squared_error

In [69]:
df_dropped1['Time']=(df_dropped1.InvoiceDate.dt.year-2010)*12+df_dropped1.InvoiceDate.dt.month

In [70]:
df_dropped1['Time']

0         12
1         12
2         12
3         12
4         12
          ..
541904    24
541905    24
541906    24
541907    24
541908    24
Name: Time, Length: 397922, dtype: int32

In [74]:
# Convert 'InvoiceDate' to datetime object, if not already
df_dropped1['InvoiceDate'] = pd.to_datetime(df_dropped1['InvoiceDate'])

# Convert numeric columns to strings if needed
df_dropped1['InvoiceDate'] = df_dropped1['InvoiceDate'].astype(str)

# Group by monthly frequency
monthly_df = df_dropped1.groupby(pd.Grouper(key='InvoiceDate', freq='M')).sum()

print(monthly_df)

TypeError: Only valid with DatetimeIndex, TimedeltaIndex or PeriodIndex, but got an instance of 'Index'

In [75]:
monthly_df.reset_index(inplace=True)

NameError: name 'monthly_df' is not defined

In [58]:
monthly_df

NameError: name 'daily_df' is not defined

In [76]:
from __future__ import division
from keras.optimizers import Adam
import numpy as np
import matplotlib.pyplot as plt
from datetime import datetime, timedelta, date
from sklearn.model_selection import KFold, cross_val_score, train_test_split
from keras.layers import LSTM
#from keras.utils import np_utils
from keras.callbacks import EarlyStopping
from keras.models import Sequential
from keras.layers import Dense
import keras
#import plotly.graph_objs as go
#import plotly.offline as pyoff
#import plotly.plotly as py
import warnings
import pandas as pd
%matplotlib inline

warnings.filterwarnings("ignore")


#import Keras

#initiate plotly
#pyoff.init_notebook_mode()

#read the data in csv
#df_sales = pd.read_csv('sales_data.csv')

#convert date field from string to datetime
df_dropped1['Time'] = pd.to_datetime(df_dropped1['Time'])

#show first 10 rows
df_dropped1.head(10)

TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

In [77]:
df_sales = df_dropped1
df_sales.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,total_revenue,Category,Time
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,15.30,Decor,12
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,Decor,12
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,22.00,Decor,12
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,Kitchenware,12
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,Decor,12

In [78]:
#convert date field from string to datetime
df_sales['InvoiceDate'] = pd.to_datetime(df_sales['InvoiceDate'])

In [79]:
#represent month in date field as its first day
df_sales['InvoiceDate'] = df_sales['InvoiceDate'].dt.year.astype(
    'str') + '-' + df_sales['InvoiceDate'].dt.month.astype('str') + '-01'
df_sales['InvoiceDate'] = pd.to_datetime(df_sales['InvoiceDate'])
#groupby date and sum the sales
df_sales = df_sales.groupby('InvoiceDate').total_revenue.sum().reset_index()

In [80]:
#plot monthly sales
plot_data = [
    go.Scatter(
        x=df_sales['InvoiceDate'],
        y=df_sales['total_revenue'],
    )
]
plot_layout = go.Layout(
    title='Montly Sales'
)
fig = go.Figure(data=plot_data, layout=plot_layout)
pyoff.iplot(fig)

NameError: name 'go' is not defined

In [81]:
#create a new dataframe to model the difference
df_diff = df_sales.copy()
#add previous sales to the next row
df_diff['prev_sales'] = df_diff['total_revenue'].shift(1)
#drop the null values and calculate the difference
df_diff = df_diff.dropna()
df_diff['diff'] = (df_diff['total_revenue'] - df_diff['prev_sales'])
df_diff.head(10)

   InvoiceDate  total_revenue  prev_sales        diff
1   2011-01-01     492261.440  572713.890  -80452.450
2   2011-02-01     447137.350  492261.440  -45124.090
3   2011-03-01     595500.760  447137.350  148363.410
4   2011-04-01     469200.361  595500.760 -126300.399
5   2011-05-01     678594.560  469200.361  209394.199
6   2011-06-01     661213.690  678594.560  -17380.870
7   2011-07-01     600091.011  661213.690  -61122.679
8   2011-08-01     645343.900  600091.011   45252.889
9   2011-09-01     952838.382  645343.900  307494.482
10  2011-10-01    1039318.790  952838.382   86480.408

In [82]:
#plot sales diff
plot_data = [
    go.Scatter(
        x=df_diff['InvoiceDate'],
        y=df_diff['diff'],
    )
]
plot_layout = go.Layout(
    title='Montly Sales Diff'
)
fig = go.Figure(data=plot_data, layout=plot_layout)
pyoff.iplot(fig)

NameError: name 'go' is not defined

In [83]:
#create dataframe for transformation from time series to supervised
df_supervised = df_diff.drop(['prev_sales'], axis=1)
#adding lags
for inc in range(1, 13):
    field_name = 'lag_' + str(inc)
df_supervised[field_name] = df_supervised['diff'].shift(inc)
#drop null values
df_supervised = df_supervised.dropna().reset_index(drop=True)

In [84]:
#create dataframe for transformation from time series to supervised
df_supervised = df_diff.drop(['prev_sales'], axis=1)

#adding lags
for inc in range(1, 7):
    field_name = 'lag_' + str(inc)
    df_supervised[field_name] = df_supervised['diff'].shift(inc)

#drop null values
df_supervised = df_supervised.dropna().reset_index(drop=True)

In [85]:
df_supervised.head(20)

,InvoiceDate,total_revenue,diff,lag_1,lag_2,lag_3,lag_4,lag_5,lag_6
0,2011-07-01,600091.011,-61122.679,-17380.870,209394.199,-126300.399,148363.410,-45124.090,-80452.450
1,2011-08-01,645343.900,45252.889,-61122.679,-17380.870,209394.199,-126300.399,148363.410,-45124.090
2,2011-09-01,952838.382,307494.482,45252.889,-61122.679,-17380.870,209394.199,-126300.399,148363.410
3,2011-10-01,1039318.790,86480.408,307494.482,45252.889,-61122.679,-17380.870,209394.199,-126300.399
4,2011-11-01,1161817.380,122498.590,86480.408,307494.482,45252.889,-61122.679,-17380.870,209394.199
5,2011-12-01,349723.190,-812094.190,122498.590,86480.408,307494.482,45252.889,-61122.679,-17380.870

In [86]:
# Import statsmodels.formula.api
from sklearn.preprocessing import MinMaxScaler
import statsmodels.formula.api as smf
# Define the regression formula
model = smf.ols(formula='diff ~ lag_1', data=df_supervised)
# Fit the regression
model_fit = model.fit()
# Extract the adjusted r-squared
regression_adj_rsq = model_fit.rsquared_adj

-0.2378937102768024

In [87]:
#import MinMaxScaler and create a new dataframe for LSTM model
from sklearn.preprocessing import MinMaxScaler
df_model = df_supervised.drop(['total_revenue', 'InvoiceDate'], axis=1)
#split train and test set
train_set, test_set = df_model[0:-3].values, df_model.values

In [88]:
df_model

,diff,lag_1,lag_2,lag_3,lag_4,lag_5,lag_6
0,-61122.679,-17380.870,209394.199,-126300.399,148363.410,-45124.090,-80452.450
1,45252.889,-61122.679,-17380.870,209394.199,-126300.399,148363.410,-45124.090
2,307494.482,45252.889,-61122.679,-17380.870,209394.199,-126300.399,148363.410
3,86480.408,307494.482,45252.889,-61122.679,-17380.870,209394.199,-126300.399
4,122498.590,86480.408,307494.482,45252.889,-61122.679,-17380.870,209394.199
5,-812094.190,122498.590,86480.408,307494.482,45252.889,-61122.679,-17380.870

In [89]:
#apply Min Max Scaler
scaler = MinMaxScaler(feature_range=(-1, 1))
scaler = scaler.fit(train_set)
# reshape training set
train_set = train_set.reshape(train_set.shape[0], train_set.shape[1])
train_set_scaled = scaler.transform(train_set)
# reshape test set
test_set = test_set.reshape(test_set.shape[0], test_set.shape[1])
test_set_scaled = scaler.transform(test_set)

In [90]:
X_train, y_train = train_set_scaled[:, 1:], train_set_scaled[:, 0:1]
X_train = X_train.reshape(X_train.shape[0], 1, X_train.shape[1])
X_test, y_test = test_set_scaled[:, 1:], test_set_scaled[:, 0:1]
X_test = X_test.reshape(X_test.shape[0], 1, X_test.shape[1])

In [91]:
from keras.models import Sequential
from keras.layers import LSTM, Dense

model = Sequential()
model.add(LSTM(4, batch_input_shape=(
    1, X_train.shape[1], X_train.shape[2]), stateful=True))
model.add(Dense(1))
model.compile(loss='mean_squared_error', optimizer='adam')

# Replace nb_epoch with epochs
for epoch in range(100):
    model.fit(X_train, y_train, epochs=100,
              batch_size=1, verbose=1, shuffle=False)
    model.reset_states()

TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

In [ ]:
model = Sequential()
model.add(LSTM(4, batch_input_shape=(1, X_train.shape[1],
                                     X_train.shape[2]), stateful=True))
model.add(Dense(1))
model.compile(loss='mean_squared_error', optimizer='adam')
model.fit(X_train, y_train, epochs=100, batch_size=1, verbose=1,
          shuffle=False)

In [ ]:
y_pred = model.predict(X_test, batch_size=1)
#for multistep prediction, you need to replace X_test values with the
#predictions coming from t-1

In [ ]:
# Reshape y_pred
y_pred = y_pred.reshape(y_pred.shape[0], 1, y_pred.shape[1])

# Rebuild test set for inverse transform
pred_test_set = []
for index in range(0, len(y_pred)):
    print(np.concatenate([y_pred[index], X_test[index]], axis=1))
    pred_test_set.append(np.concatenate(
        [y_pred[index], X_test[index]], axis=1))

# Reshape pred_test_set
pred_test_set = np.array(pred_test_set)
pred_test_set = pred_test_set.reshape(
    pred_test_set.shape[0], pred_test_set.shape[2])

# Inverse transform
pred_test_set_inverted = scaler.inverse_transform(pred_test_set)

In [ ]:
#create dataframe that shows the predicted sales
result_list = []
sales_dates = list(df_sales[-7:].InvoiceDate)
act_sales = list(df_sales[-7:].total_revenue)

for index in range(0, len(pred_test_set_inverted)):
    result_dict = {}
    pred_value = pred_test_set_inverted[index][0] + act_sales[index]

    # Check for NaN and replace with a default value (e.g., 0)
    if pd.notna(pred_value):
        result_dict['pred_value'] = int(pred_value)
    else:
        result_dict['pred_value'] = 0

    result_dict['InvoiceDate'] = sales_dates[index + 1]
    result_list.append(result_dict)

df_result = pd.DataFrame(result_list)
#for multistep prediction, replace act_sales with the predicted sales

In [ ]:
df_sales_pred.head(20)

In [ ]:
#merge with actual sales dataframe
df_sales_pred = pd.merge(df_sales, df_result, on='InvoiceDate', how='left')
#plot actual and predicted
plot_data = [
    go.Scatter(
        x=df_sales_pred['InvoiceDate'],
        y=df_sales_pred['total_revenue'],
        name='actual'
    ),
    go.Scatter(
        x=df_sales_pred['InvoiceDate'],
        y=df_sales_pred['pred_value'],
        name='predicted'
    )
]
plot_layout = go.Layout(
    title='Sales Prediction'
)
fig = go.Figure(data=plot_data, layout=plot_layout)
pyoff.iplot(fig)